import { useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { Download, Upload, ArrowRight } from 'lucide-react';
import { useData } from '../App';
import { categories, activities } from '../data/catalog';
import { importProgress } from '../lib/storage';
import styles from './Pages.module.css';
export function ProgressPage(){
  const {progress,refresh,storageError}=useData();const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const input=useRef<HTMLInputElement>(null);
  const attempts=progress.results.flatMap(r=>r.answers);const correct=attempts.filter(a=>a.correct).length;
  function exportData(){const blob=new Blob([JSON.stringify(progress,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`english-games-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Backup exportado. Guarde esse arquivo para recuperar seu progresso.');}
  async function importData(file?:File){if(!file)return;setBusy(true);try{if(file.size>20_000_000)throw new Error('O backup deve ter até 20 MB.');await importProgress(JSON.parse(await file.text()));await refresh();setMessage('Backup importado! Seu progresso foi combinado sem duplicar atividades.');}catch(e){setMessage(e instanceof SyntaxError?'Não foi possível ler esse arquivo JSON.':(e as Error).message);}finally{setBusy(false);if(input.current)input.current.value='';}}
  return <><div className={styles.pageIntro}><span className={styles.eyebrow}>CADA PASSO CONTA</span><h1>Minha jornada <span>🌱</span></h1><p>Olha só quantas descobertas! Continue praticando no seu ritmo.</p></div><div className={styles.statsGrid}><div className="lavender"><span>📖</span><strong>{progress.visitedWordIds.length}</strong><p>palavras visitadas</p></div><div className="mint"><span>🏁</span><strong>{progress.results.length}</strong><p>atividades concluídas</p></div><div className="peach"><span>🎯</span><strong>{correct}<small> / {attempts.length}</small></strong><p>acertos / tentativas</p></div></div><p className="muted">Visitar uma palavra é o primeiro passo, não uma avaliação de domínio. Os acertos representam suas respostas nos jogos.</p><div className={styles.sectionHeading}><div><h2>Minhas descobertas por tema</h2><p>Cada categoria tem um novo mundo esperando por você.</p></div></div><div className={styles.progressList}>{categories.filter(c=>c.words.some(w=>progress.visitedWordIds.includes(w.id))||progress.results.some(r=>r.categoryId===c.id||r.answers.some(a=>c.words.some(w=>w.id===a.wordId)))).map(c=>{const ids=new Set(c.words.map(w=>w.id));const visited=progress.visitedWordIds.filter(id=>ids.has(id)).length;const answers=attempts.filter(a=>a.wordId!==null && ids.has(a.wordId));return <Link key={c.id} to={`/category/${c.id}`}><span className={`${styles.downloadIcon} ${c.color}`}>{c.emoji}</span><div><h3>{c.title}</h3><p>{visited} de {c.words.length} palavras visitadas • {answers.filter(a=>a.correct).length} acertos em {answers.length} tentativas</p><progress value={visited} max={c.words.length}/></div><ArrowRight size={18}/></Link>;})}</div>{!progress.results.length&&!progress.visitedWordIds.length&&<div className="empty"><span>✨</span><h3>Sua primeira descoberta está logo ali</h3><p>Abra uma categoria e comece pelo modo Aprender.</p><Link className="primary" to="/">Explorar categorias <ArrowRight size={17}/></Link></div>}
    {!!progress.results.length&&<><h2 className={styles.historyTitle}>Atividades recentes</h2><div className={styles.history}>{progress.results.slice(-10).reverse().map(r=><div key={r.id}><span>{activities.find(a=>a.id===r.activity)?.icon}</span><div><strong>{activities.find(a=>a.id===r.activity)?.title}</strong><p>{categories.find(c=>c.id===r.categoryId)?.title} • {new Date(r.completedAt).toLocaleDateString('pt-BR')}</p></div><small>{r.activity==='learn'?`${r.visitedWordIds.length} palavras visitadas`:`${r.answers.filter(a=>a.correct).length} / ${r.answers.length} acertos`}</small></div>)}</div></>}
    <section className={styles.backup}><div><h2>Guarde suas conquistas</h2><p>Seu progresso fica neste navegador. Exporte um backup para guardar ou levar a outro aparelho. A importação combina os dados com seu progresso atual.</p></div><div className={styles.backupActions}><button className="secondary" disabled={!!storageError} onClick={exportData}><Download size={17}/> Exportar backup</button><button className="secondary" disabled={busy||!!storageError} onClick={()=>input.current?.click()}><Upload size={17}/>{busy?'Importando…':'Importar backup'}</button><input ref={input} type="file" accept="application/json,.json" hidden onChange={e=>void importData(e.target.files?.[0])}/></div>{message&&<p role="status" className="notice">{message}</p>}</section></>;
}

