import { useState } from 'react';
import { Check, ArrowRight } from 'lucide-react';
import { shuffle } from '../lib/rules';
import type { Answer, Word } from '../types';
import type { Finish } from './GamePage';
import styles from './Games.module.css';
export function MemoryGame({words,finish}:{words:Word[];finish:Finish}){
  const [cards]=useState(()=>shuffle(shuffle(words).slice(0,6).flatMap(word=>[{word,kind:'word'},{word,kind:'image'}])));
  const [flipped,setFlipped]=useState<number[]>([]);const [matched,setMatched]=useState<string[]>([]);const [answers,setAnswers]=useState<Answer[]>([]);
  const [feedback,setFeedback]=useState('');const complete=matched.length===cards.length/2;
  function flip(index:number){if(complete||flipped.length===2||flipped.includes(index)||matched.includes(cards[index].word.id))return;
    const next=[...flipped,index];setFlipped(next);if(next.length===2){const good=cards[next[0]].word.id===cards[next[1]].word.id;setAnswers(a=>[...a,{wordId:cards[next[0]].word.id,correct:good}]);if(good){setMatched(m=>[...m,cards[index].word.id]);setFlipped([]);setFeedback('Você encontrou um par! ✨');}else setFeedback('Ainda não é o par. Guarde essas pistas!');}}
  return <><div className={styles.pairInfo}><span><strong>{matched.length}</strong> de {cards.length/2} pares</span><span>{answers.length} tentativas</span></div><h2 className={styles.question}>Uma imagem, uma palavra. Encontre os pares!</h2><div className={styles.memoryGrid}>{cards.map((card,i)=>{const done=matched.includes(card.word.id),revealed=done||flipped.includes(i);return <button key={i} className={`${styles.memoryCard} ${revealed?styles.revealed:''} ${done?styles.matched:''}`} aria-label={revealed?`${card.kind==='word'?card.word.english:card.word.portuguese}${done?', par encontrado':''}`:`Virar carta ${i+1}`} aria-pressed={revealed} disabled={done} onClick={()=>flip(i)}>{revealed?card.kind==='image'?<img src={card.word.image} alt={card.word.portuguese}/>:<span lang="en">{card.word.english}</span>:<span className={styles.cardBack}>✦</span>}{done&&<Check className={styles.pairCheck} size={17}/>}</button>;})}</div><div className={styles.pairFeedback} role="status">{feedback||'Toque em duas cartas para começar.'}</div>{flipped.length===2&&<button className="secondary" onClick={()=>{setFlipped([]);setFeedback('Vamos tentar outro par.');}}>Tentar outro par</button>}{complete&&<button className="primary" onClick={()=>finish(answers)}>Ver resultado <ArrowRight size={17}/></button>}</>;
}
export function MatchGame({words,finish}:{words:Word[];finish:Finish}){
  const [left]=useState(()=>shuffle(words).slice(0,6));const [right]=useState(()=>shuffle(left));
  const [selected,setSelected]=useState<{left:string|null;right:string|null}>({left:null,right:null});const [matched,setMatched]=useState<string[]>([]);const [answers,setAnswers]=useState<Answer[]>([]);const [feedback,setFeedback]=useState('');
  function select(side:'left'|'right',id:string){if(matched.includes(id))return;const next={...selected,[side]:id};setSelected(next);if(next.left&&next.right){const good=next.left===next.right;setAnswers(a=>[...a,{wordId:next.left!,correct:good}]);setFeedback(good?'Combinação perfeita! ✨':'Essas duas não combinam. Tente outra vez.');if(good)setMatched(m=>[...m,next.left!]);setSelected({left:null,right:null});}}
  return <><div className={styles.pairInfo}><span><strong>{matched.length}</strong> de {left.length} pares</span><span>{answers.length} tentativas</span></div><h2 className={styles.question}>Toque na palavra e na imagem que combina.</h2><div className={styles.matchBoard}><div><span className={styles.columnLabel}>PALAVRAS</span>{left.map(w=><button className={`${styles.matchItem} ${selected.left===w.id?styles.selected:''} ${matched.includes(w.id)?styles.matched:''}`} key={w.id} disabled={matched.includes(w.id)} aria-pressed={selected.left===w.id} onClick={()=>select('left',w.id)} lang="en">{w.english}{matched.includes(w.id)&&<Check size={17}/>}</button>)}</div><div><span className={styles.columnLabel}>IMAGENS</span>{right.map(w=><button className={`${styles.matchItem} ${selected.right===w.id?styles.selected:''} ${matched.includes(w.id)?styles.matched:''}`} key={w.id} disabled={matched.includes(w.id)} aria-label={w.portuguese} aria-pressed={selected.right===w.id} onClick={()=>select('right',w.id)}><img src={w.image} alt=""/>{matched.includes(w.id)&&<Check size={17}/>}</button>)}</div></div><p className={styles.pairFeedback} role="status">{feedback||'Você também pode começar pela imagem.'}</p>{matched.length===left.length&&<button className="primary" onClick={()=>finish(answers)}>Ver resultado <ArrowRight size={17}/></button>}</>;
}
